#!/bin/bash -e
TARGET=$1

if [ -z "$TARGET" ]; then
  echo TARGET missing
  exit 1
fi

mkdir -p "$TARGET"
stack install stronghold:stronghold --local-bin-path "$TARGET"

# Packager symlinks
mkdir -p "$TARGET/.packager/bin"
ln -s ../../stronghold "$TARGET/.packager/bin/stronghold"
